# Generated by Django 4.0 on 2021-12-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('coaches', models.CharField(choices=[('a', '3ac'), ('b', '2ac'), ('c', '1ac')], max_length=10)),
            ],
        ),
    ]
