# Generated by Django 4.0 on 2021-12-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrainModels',
        ),
    ]
