# Generated by Django 4.0 on 2021-12-11 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0002_delete_trainmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_number', models.IntegerField()),
                ('from_date', models.DateField()),
                ('end_date', models.DateField()),
                ('coaches', models.CharField(choices=[('a', '3ac'), ('b', '2ac'), ('c', '1ac')], max_length=10)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('departure_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_station', models.CharField(max_length=45)),
                ('dest_station', models.CharField(max_length=50)),
            ],
        ),
    ]
