# Generated by Django 4.0 on 2021-12-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contactdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDetail',
        ),
        migrations.DeleteModel(
            name='TrainModels',
        ),
    ]
