# Generated by Django 4.0 on 2021-12-12 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_signupmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupModel',
        ),
    ]
