# Generated by Django 4.0 on 2021-12-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_delete_signupmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train_booking_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('no_of_persons', models.IntegerField()),
                ('aadhar', models.BigIntegerField(max_length=12)),
                ('type_of_coach', models.CharField(choices=[('a', '3ac'), ('b', '2ac'), ('c', '1ac')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('arrival_place', models.CharField(max_length=25)),
                ('departure_place', models.CharField(max_length=25)),
            ],
        ),
    ]
