# Generated by Django 4.0 on 2021-12-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_train_booking_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_booking_model',
            name='aadhar',
            field=models.BigIntegerField(),
        ),
    ]
