# Generated by Django 4.0 on 2021-12-13 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_train_booking_model_aadhar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train_booking_model',
            old_name='aadhar',
            new_name='aadhar_number',
        ),
    ]
