# Generated by Django 4.0 on 2021-12-13 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_rename_aadhar_train_booking_model_aadhar_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonsDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='train_booking_model',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
