# Generated by Django 4.0 on 2021-12-13 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0013_alter_train_booking_model_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsdetailsmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personalTrainDetails', to='auth.user'),
        ),
        migrations.AddField(
            model_name='train_booking_model',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookTrains', to='auth.user'),
        ),
    ]
