# Generated by Django 4.0 on 2021-12-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_personsdetailsmodel_user_train_booking_model_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personsdetailsmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='train_booking_model',
            name='user',
        ),
    ]
