# Generated by Django 4.0 on 2021-12-13 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0015_remove_personsdetailsmodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_booking_model',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
