# Generated by Django 4.0 on 2021-12-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_trainmodels_coaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_booking_model',
            name='type_of_coach',
            field=models.BooleanField(choices=[('a', '3ac'), ('b', '2ac'), ('c', '1ac')], default='a'),
        ),
    ]
