# Generated by Django 4.0 on 2021-12-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_train_booking_model_type_of_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_booking_model',
            name='type_of_coach',
            field=models.CharField(choices=[('a', '3ac'), ('b', '2ac'), ('c', '1ac')], max_length=10),
        ),
    ]
