# Generated by Django 4.0 on 2021-12-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_alter_train_booking_model_type_of_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainmodels',
            name='coaches',
            field=models.CharField(blank=True, choices=[('a', '3ac'), ('b', '2ac'), ('c', '1ac')], default='a', max_length=10),
        ),
    ]
