# Generated by Django 4.0 on 2021-12-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_trainmodels_coaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainmodels',
            name='coaches',
            field=models.CharField(choices=[('a', '3ac'), ('b', '2ac'), ('c', '1ac')], max_length=10),
        ),
    ]
