# Generated by Django 4.0 on 2021-12-16 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_alter_trainmodels_coaches'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_booking_model',
            name='trainName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.trainmodels'),
        ),
    ]
