# Generated by Django 4.0 on 2021-12-16 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_train_booking_model_trainname'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_booking_model',
            name='arrivalTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivalTime', to='pages.trainmodels'),
        ),
        migrations.AddField(
            model_name='train_booking_model',
            name='destinationStation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destStation', to='pages.trainmodels'),
        ),
        migrations.AlterField(
            model_name='train_booking_model',
            name='trainName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainName', to='pages.trainmodels'),
        ),
    ]
