# Generated by Django 4.0 on 2021-12-16 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_train_booking_model_arrivaltime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train_booking_model',
            name='arrivalTime',
        ),
    ]
