# Generated by Django 4.0 on 2021-12-16 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_remove_train_booking_model_destinationstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_booking_model',
            name='trainName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainName', to='pages.trainmodels'),
        ),
    ]
