# Generated by Django 4.0 on 2021-12-16 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_alter_train_booking_model_trainname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train_booking_model',
            old_name='arrival_place',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='train_booking_model',
            name='departure_place',
        ),
    ]
